application:
  incidentApiUrl: ${INCIDENT_API_URL}
  incidentResourcePath: ${INCIDENT_RESOURCE_PATH}
  redisHost: ${REDISCACHE_HOSTNAME}
  redisPort: ${REDISCACHE_PORT}
  primaryKey: ${REDISCACHE_PRIMARY_KEY}
  redisSslPort: ${REDISCACHE_SSLPORT}
  
azure:
  storage:
    account:
      name: ${AZURE_STORAGE_ACCOUNT}
      key: ${AZURE_STORAGE_ACCESS_KEY}
      blobContainer: ${AZURE_STORAGE_BLOB_CONTAINER}
      queue: ${AZURE_STORAGE_QUEUE}

logging:
  level: info

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 3mb
      max-request-size: 20mb
  application:
    name: DevCamp demo App
  profiles:
    active: default

server:
  port: 8080

security:
  oauth2:
    client:
      clientId: ${AAD_CLIENT_ID}
      clientSecret: ${AAD_CLIENT_SECRET}
      accessTokenUri: https://login.microsoftonline.com/common/oauth2/v2.0/token
      userAuthorizationUri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
      tokenName: access_token
      authenticationScheme: header
      clientAuthenticationScheme: form
      preEstablishedRedirectUri: ${AAD_RETURN_URL}
      scope:  openid,profile,User.Read, Mail.Send
    resource:
      userInfoUri: https://graph.microsoft.com/v1.0/me