// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace IncidentAPI.Models
{
    public partial class Incident
    {
        private string _city;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string City
        {
            get { return this._city; }
            set { this._city = value; }
        }
        
        private DateTimeOffset? _created;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Created
        {
            get { return this._created; }
            set { this._created = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private string _firstName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FirstName
        {
            get { return this._firstName; }
            set { this._firstName = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _imageUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ImageUri
        {
            get { return this._imageUri; }
            set { this._imageUri = value; }
        }
        
        private bool? _isEmergency;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsEmergency
        {
            get { return this._isEmergency; }
            set { this._isEmergency = value; }
        }
        
        private DateTimeOffset? _lastModified;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? LastModified
        {
            get { return this._lastModified; }
            set { this._lastModified = value; }
        }
        
        private string _lastName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string LastName
        {
            get { return this._lastName; }
            set { this._lastName = value; }
        }
        
        private string _outageType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string OutageType
        {
            get { return this._outageType; }
            set { this._outageType = value; }
        }
        
        private string _phoneNumber;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PhoneNumber
        {
            get { return this._phoneNumber; }
            set { this._phoneNumber = value; }
        }
        
        private bool? _resolved;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Resolved
        {
            get { return this._resolved; }
            set { this._resolved = value; }
        }
        
        private string _sortKey;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SortKey
        {
            get { return this._sortKey; }
            set { this._sortKey = value; }
        }
        
        private string _state;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string State
        {
            get { return this._state; }
            set { this._state = value; }
        }
        
        private string _street;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Street
        {
            get { return this._street; }
            set { this._street = value; }
        }
        
        private string _thumbnailUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ThumbnailUri
        {
            get { return this._thumbnailUri; }
            set { this._thumbnailUri = value; }
        }
        
        private string _zipCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ZipCode
        {
            get { return this._zipCode; }
            set { this._zipCode = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Incident class.
        /// </summary>
        public Incident()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Incident
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.City != null)
            {
                outputObject["City"] = this.City;
            }
            if (this.Created != null)
            {
                outputObject["Created"] = this.Created.Value;
            }
            if (this.Description != null)
            {
                outputObject["Description"] = this.Description;
            }
            if (this.FirstName != null)
            {
                outputObject["FirstName"] = this.FirstName;
            }
            if (this.ID != null)
            {
                outputObject["id"] = this.ID;
            }
            if (this.ImageUri != null)
            {
                outputObject["ImageUri"] = this.ImageUri;
            }
            if (this.IsEmergency != null)
            {
                outputObject["IsEmergency"] = this.IsEmergency.Value;
            }
            if (this.LastModified != null)
            {
                outputObject["LastModified"] = this.LastModified.Value;
            }
            if (this.LastName != null)
            {
                outputObject["LastName"] = this.LastName;
            }
            if (this.OutageType != null)
            {
                outputObject["OutageType"] = this.OutageType;
            }
            if (this.PhoneNumber != null)
            {
                outputObject["PhoneNumber"] = this.PhoneNumber;
            }
            if (this.Resolved != null)
            {
                outputObject["Resolved"] = this.Resolved.Value;
            }
            if (this.SortKey != null)
            {
                outputObject["SortKey"] = this.SortKey;
            }
            if (this.State != null)
            {
                outputObject["State"] = this.State;
            }
            if (this.Street != null)
            {
                outputObject["Street"] = this.Street;
            }
            if (this.ThumbnailUri != null)
            {
                outputObject["ThumbnailUri"] = this.ThumbnailUri;
            }
            if (this.ZipCode != null)
            {
                outputObject["ZipCode"] = this.ZipCode;
            }
            return outputObject;
        }
    }
}
