#!/bin/bash
set AZURE_STORAGE_ACCESS_KEY=yMH9b0E3u5Cf9sZTwxwoQXsM90ygX/VO5qyJmRStJ1NR5cr8xiLm788ELahxTtzL376BGJZG8SOdx5PnlZpkbA==
set AZURE_STORAGE_ACCOUNT=incidentblobstg32csxy6h3
set AZURE_STORAGE_BLOB_CONTAINER=images
set AZURE_STORAGE_QUEUE=thumbnails
set INCIDENT_API_URL=http://incidentapi32csxy6h3sbku.azurewebsites.net
set INCIDENT_RESOURCE_PATH=/incidents
set REDISCACHE_HOSTNAME=incidentcache32csxy6h3sbku.redis.cache.windows.net
set REDISCACHE_PORT=6379
set REDISCACHE_PRIMARY_KEY=Fw1IK6VXPILlqXNOiUBd9Kl8nyWLLBvR2QwosWZkRLY=
set REDISCACHE_SSLPORT=6380
gradle bootRun
